classe/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="classe"
urlpatterns = [
    path('classe_register/', views.classe_register,name="classe_register"),
    path('classe_list/', views.classe_list,name="classe_list"),
    url(r'classe_list/(?P<id>[0-9]+)/$',views.classe_listing,name="classe_listing"),
    url(r'classe_update/(?P<id>[0-9]+)/$',views.classe_update,name="classe_update"),
    url(r'classe_delete/(?P<id>[0-9]+)/$',views.classe_delete,name="classe_delete"),    
]

note/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="note"
urlpatterns = [
    path('note_register/', views.note_register,name="note_register"),
    path('note_list/', views.note_list,name="note_list"),
    url(r'note_list/(?P<id>[0-9]+)/$',views.note_listing,name="note_listing"),
    url(r'note_update/(?P<id>[0-9]+)/$',views.note_update,name="note_update"),
    url(r'note_read/(?P<id>[0-9]+)/$',views.note_read,name="note_read"),
    url(r'note_delete/(?P<id>[0-9]+)/$',views.note_delete,name='note_delete'),    
]

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path
from django.conf.urls import url,include
from compte.models import Profile,Etablissement,Classe,Note,Enseignant
from django.contrib.auth import views
#from compte.forms import LoginForm
from .import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns =[
    #path('admin/', admin.site.urls),
    
   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# On ajoute dans i18n_patterns la liste des urls des pages a traduire 
urlpatterns += i18n_patterns(
    #url(r'^{}'.format(settings.DJANGO_ADMIN_URL), admin.site.urls),
    path('',views.home,name='home'),
    path('note/', include('note.urls',namespace="note")),
    path('etablissement/', include('etablissement.urls',namespace="etablissement")),
    path('enseignant/', include('enseignant.urls',namespace="enseignant")),
    path('compte/', include('compte.urls',namespace="compte")),
    path('classe/', include('classe.urls',namespace="classe")),
) 

classe/models.py
from django.db import models

# Create your models here.

classe/forms.py
from django.contrib.auth.forms import AuthenticationForm
from compte.models import Etablissement ,Classe ,Profile
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column	



class classe_form_register(ModelForm):
    class Meta:
        model = Classe
        fields = ['classe_code','classe_desig']
        labels = {
               'classe_code': _('etablissement:'),
               'classe_desig': _('classe Designation:'),
               }


    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.helper = FormHelper()
          self.helper.layout = Layout(
              Row(
               Column('classe_code', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
              ),
              Row(
               Column('classe_desig', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
          ),
    Submit('submit', 'Enregistrer')
     )


class classe_form_Updater(ModelForm):
    class Meta:
        model = Classe
        fields = ['classe_code','classe_desig']
        labels = {
               'classe_code': _('etablissement:'),
               'classe_desig': _('classe Designation:'),
               }


    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.helper = FormHelper()
          self.helper.layout = Layout(
              Row(
               Column('classe_code', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
              ),
              Row(
               Column('classe_desig', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
          ),
    Submit('submit', 'Enregistrer')
     )

classe/views.py
from django.core import serializers
from django.contrib import messages
from django.shortcuts import render ,redirect
from django.http import HttpResponse ,HttpResponseRedirect
#from etablissement import forms
from compte.models import Classe ,Etablissement
from django.views.generic import CreateView
from .forms import classe_form_register ,classe_form_Updater
from django_tables2 import RequestConfig
from django.views.generic.edit import UpdateView , DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from rest_framework import generics


def classe_register(request):
    if request.method == 'POST':
        form = classe_form_register(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Enregistrement avec succés')
            return redirect('classe:classe_list')

    else:
        form = classe_form_register()
    return render(request, 'classe_register.html', {'form': form})

def classe_list(request):
    all_classes = Classe.objects.all()
    return render(request, 'classe_list.html', {'all_classes': all_classes})

def classe_listing(request,id):
    etablissement = Etablissement.objects.get(id=id)
    all_classes = Classe.objects.filter(classe_code=etablissement)
    return render(request, 'classe_list.html', {'all_classes': all_classes})

def classe_update(request,id):
    if request.method == 'POST':
        obj=Classe.objects.get(id=id)
        form =classe_form_Updater(request.POST or None, instance= obj)
        
        if form.is_valid():
        
            obj= form.save(commit=False)
            obj.save()
            messages.success(request,'Mise à jour avec succés')
            return redirect('classe:classe_list')#, {'all_immobs': Immob.objects.all()})
    else:
        classes = Classe.objects.get(id=id)
        form=classe_form_Updater(instance=classes)
    
    return render(request, 'classe_update.html', {'form': form})

def classe_delete(request,id):
    instance = Classe.objects.get(id=id)
    instance.delete()
    return redirect('classe:classe_list')

classe/templates/classe_list.html
{% extends 'base.html' %}
{% load static %}
{% load fontawesome %}
{% block content%}
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!--link rel="stylesheet" href="{% static 'css/styles.css' %}"-->
<caption>listes des classes</caption>
        <table id ="table_id" class = "table table-bordered">
            {% fontawesome_stylesheet %}
        <thead class = "alert-success">
            <tr>        
                <td>Etablissement :</td>
                <td>classe :</td>
                <td>Action:</td>
            </tr>
        </thead>
        <tbody>
            {% for classe in all_classes %}
            <tr>     
                    <td>{{ classe.classe_code}}</td>
                    <td>{{ classe.classe_desig}}</td>
                    <td>
                        <a class="btn btn-info btn-sm"  href="{% url 'classe:classe_update' classe.id %}">{% fontawesome_icon 'pencil' large=True spin=False color='white' title='Modifier' %}</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'classe:classe_delete' classe.id %}">{% fontawesome_icon 'trash' large=True spin=False color='white' title='Supprimer' %}</a>     
                        <a class="btn btn-warning btn-sm" href="{% url 'note:note_listing' classe.id %}">{% fontawesome_icon 'clipboard' large=True spin=False color='white' title='les notes'%}</a>  
                    </td> 
            </tr>
           {% endfor %}
        </tbody>
        </table> 
{% endblock %}  
{% block js %}
<link rel="stylesheet" type="text/css" href="{% static '/DataTables/datatables.min.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static '/DataTables/datatables.min.css' %}"/>
<script type="text/javascript" src="{% static '/DataTables/datatables.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.3/b-1.5.6/b-colvis-1.5.6/b-html5-1.5.6/b-print-1.5.6/cr-1.5.0/fc-3.2.5/kt-2.5.0/r-2.2.2/rg-1.1.0/rr-1.2.4/sl-1.3.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.3/b-1.5.6/b-colvis-1.5.6/b-html5-1.5.6/b-print-1.5.6/cr-1.5.0/fc-3.2.5/kt-2.5.0/r-2.2.2/rg-1.1.0/rr-1.2.4/sl-1.3.0/datatables.min.js"></script>
<script>
    $(document).ready( function () {
    $('#table_id').DataTable({
        
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
        },
    dom: 'B<"clear">lfrtip',
    buttons:{
        name: 'primary',
        buttons: ['copy','csv','excel',{
            extend: 'pdf',
            orientation: 'landscape',
            pageSize: 'LEGAL'
          }]
        
    }}
    
    
    );
   
        

    });

 
</script>
{% endblock %}

classe/templates/classe_register.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block content %}
{% crispy form %}
{% endblock %}

classe/templates/classe_update.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block content %}
{% crispy form %}
{% endblock %}