classe/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="classe"
urlpatterns = [
    path('classe_register/', views.classe_register,name="classe_register"),
    path('classe_list/', views.classe_list,name="classe_list"),
    url(r'classe_list/(?P<id>[0-9]+)/$',views.classe_listing,name="classe_listing"),
    url(r'classe_update/(?P<id>[0-9]+)/$',views.classe_update,name="classe_update"),
    url(r'classe_delete/(?P<id>[0-9]+)/$',views.classe_delete,name="classe_delete"),    
]

compte/urls.py
from django.urls import path
from . import views
app_name="compte"
urlpatterns = [
    path('login/', views.login_user,name="login"),
    path('logout/',views.logout_user,name="logout"),
    path('register/',views.user_registration,name="register")
]

enseignant/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="enseignant"
urlpatterns = [
    path('enseignant_register/', views.enseignant_register,name="enseignant_register"),
    path('enseignant_list/', views.enseignantlist,name="enseignant_list"),
    url(r'enseignant_update/(?P<id>[0-9]+)/$',views.enseignant_update,name="enseignant_update"),
    url(r'enseignant_delete/(?P<id>[0-9]+)/$',views.enseignant_delete,name='enseignant_delete'),    
]

etablissement/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="etablissement"
urlpatterns = [
    path('etablissement_register/', views.etablissement_register,name="etab_register"),
    path('etablissement_list/', views.etablissement_list,name="etab_list"),
    url(r'etablissement_update/(?P<id>[0-9]+)/$',views.etablissement_update,name="etab_update"),
    url(r'etablissement_delete/(?P<id>[0-9]+)/$',views.etablissement_delete,name='etab_delete'),    
]

note/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="note"
urlpatterns = [
    path('note_register/', views.note_register,name="note_register"),
    path('note_list/', views.note_list,name="note_list"),
    url(r'note_list/(?P<id>[0-9]+)/$',views.note_listing,name="note_listing"),
    url(r'note_update/(?P<id>[0-9]+)/$',views.note_update,name="note_update"),
    url(r'note_read/(?P<id>[0-9]+)/$',views.note_read,name="note_read"),
    url(r'note_delete/(?P<id>[0-9]+)/$',views.note_delete,name='note_delete'),    
]

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path
from django.conf.urls import url,include
from compte.models import Profile,Etablissement,Classe,Note,Enseignant
from django.contrib.auth import views
#from compte.forms import LoginForm
from .import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns =[
    #path('admin/', admin.site.urls),
    
   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# On ajoute dans i18n_patterns la liste des urls des pages a traduire 
urlpatterns += i18n_patterns(
    #url(r'^{}'.format(settings.DJANGO_ADMIN_URL), admin.site.urls),
    path('',views.home,name='home'),
    path('note/', include('note.urls',namespace="note")),
    path('etablissement/', include('etablissement.urls',namespace="etablissement")),
    path('enseignant/', include('enseignant.urls',namespace="enseignant")),
    path('compte/', include('compte.urls',namespace="compte")),
    path('classe/', include('classe.urls',namespace="classe")),
) 

templates/includes/navbar.html
{% load static %}
{% load i18n %}
{% load fontawesome %}
{% fontawesome_stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static '/css/navbar_styles.css' %}">
 <nav class="navbar navbar-expand-lg navbar-light bg-light"> 
  <!--a class="navbar-brand" href="#">Menu</a-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-item nav-link active" href="{% url 'home' %}"><span style="font-size: 15px;">{% fontawesome_icon 'home' large=True spin=False color='black' title='Home' %}</span></a> <!--Home <span class="sr-only">(current)</span>-->
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          les Notices
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'note:note_register' %}">Une nouvelle Notices</a>
          <a class="dropdown-item" href="{% url 'note:note_list' %}">Programme des Notices</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Etablissements
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'etablissement:etab_register' %}">nouvelle Etablissement</a>
          <a class="dropdown-item" href="{% url 'etablissement:etab_list' %}">listes des Etablissements</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Classes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'classe:classe_register' %}">Creation des classes </a>
            <a class="dropdown-item" href="{% url 'classe:classe_list' %}">liste des classes</a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Enseignant
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'enseignant:enseignant_register' %}">Nouveau Enseignant</a>
            <a class="dropdown-item" href="{% url 'enseignant:enseignant_list'%}">Liste des Enseignants</a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
        <!--<a> class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
    </ul>
  <!--/div-->
    <div class="navbar-nav ml-auto">
        
    {% if request.user.is_authenticated %} <!--class="nav-item nav-link"--> 
    <li class="nav-item2 dropdown ">
        <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% fontawesome_icon 'user-circle' large=True spin=False color='black' title='compte' %} {{user.username}}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item2 nav-link ml-auto "  href="{% url 'compte:logout' %}">{% fontawesome_icon 'power-off' large=True spin=False color='red' title='Home' %} Déconnecter</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
    {% else %}
    <a class="nav-item nav-link" href="{% url 'compte:login' %}">{% fontawesome_icon 'sign-in-alt' large=True spin=False color='red' title='Home' %} Connecter</a>
    {% endif %}
    </div>
  </div>
</nav>