classe/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="classe"
urlpatterns = [
    path('classe_register/', views.classe_register,name="classe_register"),
    path('classe_list/', views.classe_list,name="classe_list"),
    url(r'classe_list/(?P<id>[0-9]+)/$',views.classe_listing,name="classe_listing"),
    url(r'classe_update/(?P<id>[0-9]+)/$',views.classe_update,name="classe_update"),
    url(r'classe_delete/(?P<id>[0-9]+)/$',views.classe_delete,name="classe_delete"),    
]

etablissement/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="etablissement"
urlpatterns = [
    path('etablissement_register/', views.etablissement_register,name="etab_register"),
    path('etablissement_list/', views.etablissement_list,name="etab_list"),
    url(r'etablissement_update/(?P<id>[0-9]+)/$',views.etablissement_update,name="etab_update"),
    url(r'etablissement_delete/(?P<id>[0-9]+)/$',views.etablissement_delete,name='etab_delete'),    
]

note/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="note"
urlpatterns = [
    path('note_register/', views.note_register,name="note_register"),
    path('note_list/', views.note_list,name="note_list"),
    url(r'note_list/(?P<id>[0-9]+)/$',views.note_listing,name="note_listing"),
    url(r'note_update/(?P<id>[0-9]+)/$',views.note_update,name="note_update"),
    url(r'note_read/(?P<id>[0-9]+)/$',views.note_read,name="note_read"),
    url(r'note_delete/(?P<id>[0-9]+)/$',views.note_delete,name='note_delete'),    
]

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path
from django.conf.urls import url,include
from compte.models import Profile,Etablissement,Classe,Note,Enseignant
from django.contrib.auth import views
#from compte.forms import LoginForm
from .import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns =[
    #path('admin/', admin.site.urls),
    
   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# On ajoute dans i18n_patterns la liste des urls des pages a traduire 
urlpatterns += i18n_patterns(
    #url(r'^{}'.format(settings.DJANGO_ADMIN_URL), admin.site.urls),
    path('',views.home,name='home'),
    path('note/', include('note.urls',namespace="note")),
    path('etablissement/', include('etablissement.urls',namespace="etablissement")),
    path('enseignant/', include('enseignant.urls',namespace="enseignant")),
    path('compte/', include('compte.urls',namespace="compte")),
    path('classe/', include('classe.urls',namespace="classe")),
) 

etablissement/forms.py
from django.contrib.auth.forms import AuthenticationForm
from compte.models import Etablissement ,Classe ,Profile
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column	



class etablissement_form_register(ModelForm):
    class Meta:
        model = Etablissement
        fields = ['etablissement_code','etablissement_desig']
        labels = {
               'etablissement_code': _('Etablissement Code :'),
               'etablissement_desig': _('Etablissement Designation:'),
               }


    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.helper = FormHelper()
          self.helper.layout = Layout(
              Row(
               Column('etablissement_code', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
              ),
              Row(
               Column('etablissement_desig', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
          ),
    Submit('submit', 'Enregistrer')
     )


class etablissement_form_Updater(ModelForm):
    class Meta:
        model = Etablissement
        fields = ['etablissement_code','etablissement_desig']
        labels = {
               'etablissement_code': _('Etablissement Code :'),
               'etablissement_desig': _('Etablissement Designation:'),
               }


    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.helper = FormHelper()
          self.helper.layout = Layout(
              Row(
               Column('etablissement_code', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
              ),
              Row(
               Column('etablissement_desig', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
          ),
    Submit('submit', 'Enregistrer')
     )     

etablissement/views.py
from django.core import serializers
from django.contrib import messages
from django.shortcuts import render ,redirect
from django.http import HttpResponse ,HttpResponseRedirect
#from etablissement import forms
from compte.models import Etablissement
from django.views.generic import CreateView
from .forms import etablissement_form_register ,etablissement_form_Updater
from django_tables2 import RequestConfig
from django.views.generic.edit import UpdateView , DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from rest_framework import generics
from django.core.paginator import Paginator


def etablissement_register(request):
    if request.method == 'POST':
        form = etablissement_form_register(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Enregistrement avec succés')
            return redirect('etablissement:etab_list')

    else:
        form = etablissement_form_register()
    return render(request, 'etab_register.html', {'form': form})

def etablissement_list(request):
    all_etablissements = Etablissement.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(all_etablissements,13)
    try:
        all_etablissements = paginator.page(page)
    except PageNotAnInteger:
        all_etablissements = paginator.page(1)
    except EmptyPage:
        all_etablissements = paginator.page(paginator.num_pages)
    return render(request, 'etab_list.html', {'all_etablissements': all_etablissements})

def etablissement_update(request,id):
    if request.method == 'POST':
        obj=Etablissement.objects.get(id=id)
        form =etablissement_form_Updater(request.POST or None, instance= obj) 
        if form.is_valid():
            obj= form.save(commit=False)
            obj.save()
            messages.success(request,'Mise à jour avec succés')
            return redirect('etablissement:etab_list')#, {'all_immobs': Immob.objects.all()})
    else:
        etablissment = Etablissement.objects.get(id=id)
        form =etablissement_form_Updater(instance=Etablissement.objects.get(id=id))
    
    return render(request, 'etab_update.html', {'form': form})

def etablissement_delete(request,id):
    instance = Etablissement.objects.get(id=id)
    instance.delete()
    return redirect('etablissement:etab_list')





        

etablissement/templates/etab_list.html
{% extends 'base.html' %} 
{% load fontawesome %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<div class="container"> 
    <div class="row"> 
        <!-- Blog Entries Column -->
        {% for etablissement in all_etablissements %}
        <div class="col-md-4 mt-3 left">
            <div class="card ">
                <div class="card-body">
                        {% fontawesome_stylesheet %} 
                    <h2 class="card-title">{{ etablissement.etablissement_desig}}</h2>
                    <p class="card-text text-muted h6">{{ etablissement.etablissement_code}}</p>
                    <a href="{% url 'etablissement:etab_update' etablissement.id %}" class="btn btn-info">{% fontawesome_icon 'pencil' large=True spin=False color='white' title='Modifier' %} </a>
                    <a href="{% url 'etablissement:etab_delete' etablissement.id %}" class="btn btn-danger">{% fontawesome_icon 'trash' large=True spin=False color='white' title='Modifier' %} </a> 
                    <a href="{% url 'classe:classe_listing' etablissement.id %}" class="btn btn-warning">{% fontawesome_icon 'eye' large=True spin=False color='white' title='les classes' %} </a> 
                  </div>
            </div>
        </div>
        {% endfor %}
        
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
    </div>
    {% if all_etablissements.has_other_pages %}
  <ul class="pagination">
    {% if all_etablissements.has_previous %}
      <li><a href="?page={{ all_notes.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in all_etablissements.paginator.page_range %}
      {% if all_etablissements.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if all_etablissements.has_next %}
      <li><a href="?page={{ all_notes.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

<style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 18px;
            background-color:#fdfdfd;
        }
        
        .head_text {
            color:white;
        }
        
        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }
    </style>
{% endblock %}

etablissement/templates/etab_register.html
{% extends 'base.html' %} 
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
{% crispy form %}
{% endblock %}

etablissement/templates/etab_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
{% crispy form %}
{% endblock %}