note/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views


app_name="note"
urlpatterns = [
    path('note_register/', views.note_register,name="note_register"),
    path('note_list/', views.note_list,name="note_list"),
    url(r'note_list/(?P<id>[0-9]+)/$',views.note_listing,name="note_listing"),
    url(r'note_update/(?P<id>[0-9]+)/$',views.note_update,name="note_update"),
    url(r'note_read/(?P<id>[0-9]+)/$',views.note_read,name="note_read"),
    url(r'note_delete/(?P<id>[0-9]+)/$',views.note_delete,name='note_delete'),    
]

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path
from django.conf.urls import url,include
from compte.models import Profile,Etablissement,Classe,Note,Enseignant
from django.contrib.auth import views
#from compte.forms import LoginForm
from .import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns =[
    #path('admin/', admin.site.urls),
    
   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# On ajoute dans i18n_patterns la liste des urls des pages a traduire 
urlpatterns += i18n_patterns(
    #url(r'^{}'.format(settings.DJANGO_ADMIN_URL), admin.site.urls),
    path('',views.home,name='home'),
    path('note/', include('note.urls',namespace="note")),
    path('etablissement/', include('etablissement.urls',namespace="etablissement")),
    path('enseignant/', include('enseignant.urls',namespace="enseignant")),
    path('compte/', include('compte.urls',namespace="compte")),
    path('classe/', include('classe.urls',namespace="classe")),
) 

note/models.py
from django.db import models

# Create your models here.

note/forms.py
from django.contrib.auth.forms import AuthenticationForm
from compte.models import Note
from django.forms import ModelForm ,Textarea,FileField
from django import forms
from django.utils.translation import gettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column	
from bootstrap_datepicker_plus import DatePickerInput



class note_register_form(ModelForm):
    class Meta:
        model = Note
        fields = ['titre','date_note','sujet','classe','enseignant','document']
        labels = {
               'titre': _('titre de la note:'),
               'date_note': _('date:'),
               'sujet': _('note:'),
               'classe': _('classe:'),
               'enseignant':_('Enseigant:'),
               'document':_('Document :'),
               }
        widgets= {'sujet':Textarea(),
                   'date_note':DatePickerInput(format='%d/%m/%Y'),
                   
        }

    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.helper = FormHelper()
          self.helper.layout = Layout(
              Row(
               Column('titre', css_class='form-group col-md-4 mb-0'),
               Column('date_note', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
              ),
              Row(
               Column('sujet', css_class='form-group col-md-8 mb-0'),
               css_class='form-row'
          ),
          Row(
               Column('classe', css_class='form-group col-md-4 mb-0'),
               Column('enseignant', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
          ),
          Row(
              Column('document',css_class='form-group col-md-4 mb-0'),
              css_class='form-row'
          ),
    Submit('submit', 'Enregistrer')
     ) 



class note_update_form(ModelForm):
    class Meta:
        model = Note
        fields = '__all__'
        labels = {
               'titre': _('titre de la note:'),
               'date_note': _('date:'),
               'sujet': _('note:'),
               'classe': _('classe:'),
               'enseignant':_('Enseigant:'),
               'document':_('Document'),
               }
        widgets= {'sujet':Textarea(),
                   'date_note':DatePickerInput(format='%d/%m/%Y'),
                   
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
               Column('titre', css_class='form-group col-md-4 mb-0'),
               Column('date_note', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
              ),
            Row(
               Column('sujet', css_class='form-group col-md-8 mb-0'),
               css_class='form-row'
             ),
            Row(
               Column('classe', css_class='form-group col-md-4 mb-0'),
               Column('enseignant', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
            ),
            Row (
              Column('document',css_class='form-group col-md-4 mb-0'),
              css_class='form-row'
            ),
    Submit('submit', 'Enregistrer')
    ) 

class note_read_form(ModelForm):
    class Meta:
        model = Note
        fields = ['titre' , 'date_note' , 'sujet' , 'classe']
        labels = {
               'titre': _('titre de la note:'),
               'date_note': _('date:'),
               'sujet': _('note:'),
               'classe': _('classe:'),
               'document':_('Document'),
               }
        widgets= {'sujet':Textarea(),
                   'date_note':DatePickerInput(format='%d/%m/%Y'),
        }

    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.helper = FormHelper()
          self.helper.layout = Layout(
              Row(
               Column('titre', css_class='form-group col-md-4 mb-0'),
               Column('date_note', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
              ),
              Row(
               Column('sujet', css_class='form-group col-md-8 mb-0'),
               css_class='form-row'
          ),
          Row(
               Column('classe', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
          ),
           Row(
               Column('document', css_class='form-group col-md-4 mb-0'),
               css_class='form-row'
          ),
     ) 

note/views.py
from django.core import serializers
from django.contrib import messages
from django.shortcuts import render ,redirect
from django.http import HttpResponse ,HttpResponseRedirect
from note import forms
from compte.models import Note, Classe
from django.views.generic import CreateView
from .forms import note_register_form,note_update_form,note_read_form
from django_tables2 import RequestConfig
from django.views.generic.edit import UpdateView , DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from rest_framework import generics
from django.core.paginator import Paginator
from django.core.files.storage import FileSystemStorage 


def note_register(request):
    if request.method == 'POST'  and request.FILES['document'] :
        form = note_register_form(request.POST,request.FILES)
        if form.is_valid():
            document = request.FILES['document']
            fs = FileSystemStorage()
            filename = fs.save(document.name, document)
            uploaded_file_url = fs.url(filename)
            form.save()
            messages.success(request,'Enregistrement avec succés')
            return render(request,'note_list.html',{'uploaded_file_url': uploaded_file_url})

    else:
        form = note_register_form()
    return render(request, 'note_register.html', {'form': form})

def note_list(request):
    all_notes = Note.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(all_notes,13)
    try:
        all_notes = paginator.page(page)
    except PageNotAnInteger:
        all_notes = paginator.page(1)
    except EmptyPage:
        all_notes = paginator.page(paginator.num_pages)
    return render(request, 'note_list.html', {'all_notes': all_notes})

def note_listing(request,id):
    classe = Classe.objects.get(id=id)
    all_notes= Note.objects.filter(classe=classe)
    page = request.GET.get('page',1)
    paginator = Paginator(all_notes,13)
    try:
        all_notes = paginator.page(page)
    except PageNotAnInteger:
        all_notes = paginator.page(1)
    except EmptyPage:
        all_notes = paginator.page(paginator.num_pages)
    return render(request, 'note_list.html', {'all_notes': all_notes})

def note_update(request,id):
    if request.method == 'POST':
        obj=Note.objects.get(id=id)
        form=note_update_form(request.POST or None, instance= obj)
        if form.is_valid():
            obj= form.save(commit=False)
            obj.save()
            messages.success(request,'Mise à jour avec succés')
            return redirect('note:note_list') #, {'all_immobs': Immob.objects.all()})
    else:
        note = Note.objects.get(id=id)
        form=forms.note_update_form(instance=note)
    return render(request, 'note_update.html', {'form': form})

def note_delete(request,id):
    instance = Note.objects.get(id=id)
    instance.delete()
    return redirect('note:note_list')

def note_read(request,id):
    if request.method == 'POST':
        obj=Note.objects.get(id=id)
        form=note_read_form(request.POST or None, instance= obj)
        if form.is_valid():
            obj= form.save(commit=False)
            obj.save()
            messages.success(request,'Mise à jour avec succés')
            return redirect('note:note_list') #, {'all_immobs': Immob.objects.all()})
    else:
        note = Note.objects.get(id=id)
        form=forms.note_read_form(instance=note)
    return render(request, 'note_read.html', {'form': form})

note/templates/note_list.html
{% extends 'base.html' %} 
{% load fontawesome %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<div class="container"> 
    <div class="row"> 
        <!-- Blog Entries Column -->
        {% for note in all_notes %}
        <div class="col-md-4 mt-3 left">
            <div class="card ">
                <div class="card-body">
                        {% fontawesome_stylesheet %} 
                    <h2 class="card-title">{{ note.titre }}</h2>
                    <p class="card-text text-muted h6">{{ note.classe }}{{note.enseignant}}</p>
                    <p class="card-text">{{ note.date_note}}</p> <!---->
                    <iframe src="media/documents" style="width:600px; height:500px;" frameborder="0">{{ note.document}}</iframe>
                    <!--p class="card-text">{{ note.sujet|slice:":10" }}</p-->
                    <a href="{% url 'note:note_update' note.id %}" class="btn btn-info">{% fontawesome_icon 'pencil' large=True spin=False color='white' title='Modifier' %} </a>
                    <a href="{% url 'note:note_delete' note.id %}" class="btn btn-danger">{% fontawesome_icon 'trash' large=True spin=False color='white' title='Modifier' %} </a> 
                    <a href="{% url 'note:note_read' note.id %}" class="btn btn-secondary">{% fontawesome_icon 'eye' large=True spin=False color='white' title='Lire' %} </a> 
                </div>
            </div>
        </div>
        {% endfor %}
        
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
    </div>
    {% if all_notes.has_other_pages %}
  <ul class="pagination">
    {% if all_notes.has_previous %}
      <li><a href="?page={{ all_notes.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in all_notes.paginator.page_range %}
      {% if all_notes.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if all_notes.has_next %}
      <li><a href="?page={{ all_notes.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

<style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 18px;
            background-color:#fdfdfd;
        }
        
        .head_text {
            color:white;
        }
        
        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }
    </style>
{% endblock %}

note/templates/note_read.html
{% extends 'base.html' %}  
{% load bootstrap3 %}
{% bootstrap_css %}
{% load crispy_forms_tags %}
{% block content %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% csrf_token %}
{% crispy form %}
{% endblock %} 

note/templates/note_register.html
{% extends 'base.html' %}  
{% load bootstrap3 %}
{% bootstrap_css %}
{% load crispy_forms_tags %}
{% bootstrap_javascript jquery='full' %}
{% block content %}
{{ form.media }}
{% csrf_token %}
{% crispy form %}
<form method="post" enctype="multipart/form-data">
    {#% csrf_token %#}
    <input type="file" name="document">
    <button type="submit">Upload</button>
  </form>

  {#% if uploaded_file_url %#}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {#% endif %#}

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %} 

note/templates/note_update.html
{% extends 'base.html' %}  
{% load bootstrap3 %}
{% bootstrap_css %}
{% load crispy_forms_tags %}
{% block content %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% csrf_token %}
{% crispy form %}
{% endblock %} 